<<<<<<< HEAD
# [colors.primary]
# background = '#000000'
# foreground = '#c0caf5'
#
# [bell]
# animation = "EaseOutExpo"
# duration = 0
#
# [colors]
# draw_bold_text_with_bright_colors = true
#
# [colors.bright]
# black = '#414868'
# red = '#f7768e'
# green = '#9ece6a'
# yellow = '#e0af68'
# blue = '#7aa2f7'
# magenta = '#bb9af7'
# cyan = '#7dcfff'
# white = '#c0caf5'
#
# [colors.normal]
# black = '#15161e'
# red = '#f7768e'
# green = '#9ece6a'
# yellow = '#e0af68'
# blue = '#7aa2f7'
# magenta = '#bb9af7'
# cyan = '#7dcfff'
# white = '#a9b1d6'
#
# [cursor]
# style = "Block"
# unfocused_hollow = true
#
[font]
size = 18.0
=======
[cursor]
style = "Block"
unfocused_hollow = true

[font]
size = 16.0
>>>>>>> origin/master

[font.bold]
family = "Ubuntu mono"

[font.italic]
family = "Ubuntu mono"

[font.normal]
family = "Ubuntu mono"
<<<<<<< HEAD
#
# [[mouse.bindings]]
# action = "PasteSelection"
# mouse = "Middle"
#
# [scrolling]
# history = 10000
# multiplier = 3
#
# [window.dimensions]
# columns = 80
# lines = 24
#
# [window]
# opacity = 0.8
#
# # [terminal.shell]
# # program = "/usr/bin/tmux"
# # args = ["new-session", "-A", "-s", "default"]
=======

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 10000
multiplier = 3

[window.dimensions]
columns = 80
lines = 24
>>>>>>> origin/master
