[cursor]
style = "Block"
unfocused_hollow = true

[font]
size = 16.0

[font.bold]
family = "Ubuntu mono"

[font.italic]
family = "Ubuntu mono"

[font.normal]
family = "Ubuntu mono"

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 10000
multiplier = 3

[window.dimensions]
columns = 80
lines = 24
