[bell]
animation = "EaseOutExpo"
color = "#ffffff"
duration = 0

[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "#7f7f7f"
blue = "#61afef"
cyan = "#61afef"
green = "#6b8e23"
magenta = "#654CA8"
red = "#f44747"
white = "#ffffff"
yellow = "#cd950c"

[colors.cursor]
cursor = "#40FF40"
text = "#161616"

[colors.dim]
black = "#404040"
blue = "#61afef"
cyan = "#61afef"
green = "#6b8e23"
magenta = "#654CA8"
red = "#f44747"
white = "#7f7f7f"
yellow = "#cd950c"

[colors.normal]
black = "#161616"
blue = "#61afef"
cyan = "#61afef"
green = "#6b8e23"
magenta = "#654CA8"
red = "#f44747"
white = "#ffffff"
yellow = "#cd950c"

[colors.primary]
background = "#161616"
foreground = "#ffffff"

[colors.selection]
background = "#3a3a8f"
text = "#ffffff"

[cursor]
style = "Block"
unfocused_hollow = true

[debug]
log_level = "Warn"
persistent_logging = false
print_events = false
render_timer = false

[env]
TERM = "xterm-256color"

[font]
size = 20

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "Ubuntu mono"
style = "Medium"

[font.offset]
x = -1
y = -1

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[mouse.bindings]]
action = "Copy"
mouse = "Middle"

[scrolling]
history = 10000
multiplier = 1

[selection]
save_to_clipboard = false
semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>\t"

[window]
dynamic_padding = false
dynamic_title = true
title = "Alacritty"
startup_mode = "Maximized"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 2
y = 2

[general]
live_config_reload = true
working_directory = "None"
